spring:
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/towerdb
    username: postgres
    password: postgres


  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

server:
  port : 8081