spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true
    properties:
      hibernate:
        sql=true
  datasource:
    url: jdbc:postgresql://localhost:5432/towerdb
    username: postgres
    password: postgres


  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

server:
  port : 8081

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE
kafka:
  bootstrap.servers: localhost:9092